.TH "Makefile" 3 "7 Nov 2004" "Version Revision: 1.0.0" "TEST_STRINGS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Makefile \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSRC\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBSRC\fP"
.PP
Definition at line 36 of file Makefile.
.SH "Author"
.PP 
Generated automatically by Doxygen for TEST_STRINGS from the source code.
