string_test.c
NAME
string_test.c - An sample implementation of common string functions.
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
Defines
#define BEGIN_BLOCK do {
Begin blocks for macros.
#define END_BLOCK } while (0)
And the corresponding End block.
#define ASIZE 256
The size of the alphabet -- which happens to be the ascii namespace.
#define sign(x) (x>0 ? 1 : (x<0 ? -1 : 0))
A macro to determine the signed state of an integer.
Functions
size_t manoj_strlen (const char *s)
7.21.6.3 The strlen function
int test_strlen (void)
Test the manoj_strlen function.
char * manoj_strcpy (char *dest, const char *src)
7.21.2.3 The strcpy function
int test_strcpy (void)
Test the manoj_strcpy function.
char * manoj_strncpy (char *dest, const char *src, size_t n)
7.21.2.4 The strncpy function
int test_strncpy (void)
Test the manoj_strncpy function.
char * manoj_strdup (const char *s)
The strdup function.
int test_strdup (void)
Test the manoj_strdup function.
char * manoj_strcat (char *dest, const char *src)
7.21.3.1 The strcat function
int test_strcat (void)
Test the manoj_strcat function.
char * manoj_strncat (char *dest, const char *src, size_t n)
7.21.3.2 The strncat function
int test_strncat (void)
Test the manoj_strncat function.
int manoj_strcmp (const char *s1, const char *s2)
7.21.4.2 The strcmp function Synopsis
int test_strcmp (void)
Test the manoj_strcmp function.
int manoj_strncmp (const char *s1, const char *s2, size_t n)
7.21.4.4 The strncmp function Synopsis
int test_strncmp (void)
Test the manoj_strncat function.
int strcasecmp (const char *s1, const char *s2)
int manoj_strcasecmp (const char *s1, const char *s2)
The strcasecmp function Synopsis.
int test_strcasecmp (void)
Test the manoj_strcasecmp function.
int strncasecmp (const char *s1, const char *s2, size_t n)
int manoj_strncasecmp (const char *s1, const char *s2, size_t n)
The strncasecmp function Synopsis.
int test_strncasecmp (void)
Test the manoj_strncat function.
char * manoj_strchr (const char *s, int c)
7.21.5.2 The strchr function
int test_strchr (void)
Test the manoj_strnchr function.
char * manoj_strrchr (const char *s, int c)
7.21.5.5 The strrchr function
int test_strrchr (void)
Test the manoj_strnchr function.
char * manoj_strtok (char *s, const char *delim)
7.21.5.8 The strtok function
int test_strtok (void)
Test the manoj_strtok function.
char * strtok_r (char *s, const char *delim, char **ptrptr)
char * manoj_strtok_r (char *s, const char *delim, char **ptrptr)
The strtok_r function.
int test_strtok_r (void)
Test the manoj_strtok_r function.
char * manoj_strstr (const char *haystack, const char *needle)
7.21.5.7 The strstr function
int test_strstr (void)
Test the manoj_strtsr function.
int main (void)
The main entry point for this testing routine.
Variables
const char * version
int errno
const char * strings_to_test []
A set of test strings used for regression testing.
Detailed Description
An sample implementation of common string functions.
Copyright (C) 2003 Manoj Srivastava
This is my entry for the code challenge. I do make use of the string.h header file, but only in the regression testing area, where my reimplementation of the string functions are tested against the libc versions.
These functions are rather more straight forward than those I am used to coding, and is therefore terser, and with fewer comments, than is my natural style -- all except the Boyer-Moore implementation in strstr, which was by far the most challenging.
I had fun coding this. I had forgotten how liberating C can be, coming back from C++ and java.
Definition in file string_test.c.
Define Documentation
#define ASIZE 256
The size of the alphabet -- which happens to be the ascii namespace.
Definition at line 646 of file string_test.c.
#define BEGIN_BLOCK do {
Begin blocks for macros.
Macros are dangerous if they use an if--then--else control statement, because they may be used in an if--then--else control statement themselsves, and should be enclosed in the following block to prevent problems (like dangling else statements).
Definition at line 173 of file string_test.c.
#define END_BLOCK } while (0)
And the corresponding End block.
Definition at line 178 of file string_test.c.
#define sign(x) (x>0 ? 1 : (x<0 ? -1 : 0))
A macro to determine the signed state of an integer.
This is slightly misnamed, since it does distinguish between a 0 value and positive values -- it really does return a tristate value, ideal for testing strcmp like function return values.
Definition at line 1226 of file string_test.c.
Referenced by test_strcasecmp(), test_strcmp(), test_strncasecmp(), and test_strncmp().
Function Documentation
int main (void)
The main entry point for this testing routine.
Returns:
EXIT_SUCCESS on success, EXIT_FAILURE oterwise
Definition at line 1640 of file string_test.c.
References test_strcasecmp(), test_strcat(), test_strchr(), test_strcmp(), test_strcpy(), test_strdup(), test_strlen(), test_strncasecmp(), test_strncat(), test_strncmp(), test_strncpy(), test_strrchr(), test_strstr(), test_strtok(), test_strtok_r(), and version.
int manoj_strcasecmp (const char * s1, const char * s2)
The strcasecmp function Synopsis.
Parameters:
s1 The first of two strings to be compared
s2 The second of two strings to be compared
Returns:
The strcasecmp function returns an integer
This is not an ANSI C function, but a BSD 4.4 extention. The strcasecmp function compares the string pointed to by s1 to the string pointed to by s2. The strcasecmp function returns an integer greater than, equal to, or less than zero, accordingly as the string pointed to by s1 is greater than, equal to, or less than the string s2.
Definition at line 389 of file string_test.c.
Referenced by test_strcasecmp().
char * manoj_strcat (char * dest_p, const char * src_p)
7.21.3.1 The strcat function
Parameters:
src_p The source string
dest_p The destination the source string is appended to
Returns:
The strcat function returns the value of dest_p.
The strcat function appends a copy of the string pointed to by src_p (including the terminating null character) to the end of the string pointed to by dest_p. The initial character of src_p overwrites the null character at the end of dest_p. If copying takes place between objects that overlap, the behavior is undefined.
Memory for the new string is obtained with malloc(3), and can be freed with free(3).
Definition at line 275 of file string_test.c.
Referenced by test_strcat().
char * manoj_strchr (const char * str_p, int c)
7.21.5.2 The strchr function
Parameters:
str_p The string to search in
c The character being searched for.
Returns:
A pointer to the located charcter, or NULL
The strchr function locates the first occurrence of c (converted to a char) in the string pointed to by str_p. The terminating null character is considered to be part of the string. The strchr function returns a pointer to the located character, or a null pointer if the character does not occur in the string.
Definition at line 459 of file string_test.c.
Referenced by test_strchr().
int manoj_strcmp (const char * s1, const char * s2)
7.21.4.2 The strcmp function Synopsis
Parameters:
s1 The first of two strings to be compared
s2 The second of two strings to be compared
Returns:
The strcmp function returns an integer
The strcmp function compares the string pointed to by s1 to the string pointed to by s2. The strcmp function returns an integer greater than, equal to, or less than zero, accordingly as the string pointed to by s1 is greater than, equal to, or less than the string s2.
Definition at line 321 of file string_test.c.
Referenced by test_strcmp().
char * manoj_strcpy (char * dest_p, const char * src_p)
7.21.2.3 The strcpy function
Parameters:
src_p The source string
dest_p The destination the source string is copied to
Returns:
The strcpy function returns the value of dest_p.
The strcpy function copies the string pointed to by src_p (including the terminating null character) into the array pointed to by dest_p. If copying takes place between objects that overlap, the behavior is undefined.
Definition at line 209 of file string_test.c.
Referenced by test_strcpy().
char * manoj_strdup (const char * src_p)
The strdup function.
Parameters:
src_p The source string
Returns:
The strdup function returns a copy of the input string, or NULL
This is not an ANSI C standard function, so no reference exists. The strdup() function returns a pointer to a new string which is a duplicate of the string src_p. Memory for the new string is obtained with malloc(3), and can be freed with free(3).
Definition at line 253 of file string_test.c.
Referenced by test_strdup().
size_t manoj_strlen (const char * src_p)
7.21.6.3 The strlen function
Parameters:
src_p A pointer to the char array to whose length is required
Returns:
The strlen() function returns the number of characters in src_p
The strlen function computes the length of the string pointed to by src_p. The strlen function returns the number of characters that precede the null character.
Definition at line 191 of file string_test.c.
Referenced by test_strlen().
int manoj_strncasecmp (const char * s1, const char * s2, size_t n)
The strncasecmp function Synopsis.
Parameters:
s1 The first of two strings to be compared
s2 The second of two strings to be compared
n The number of bytes compared
Returns:
The strncasecmp function returns an integer
This is not an ANSI C function, but a BSD 4.4 extention. The strncasecmp function compares not more than n characters (characters that follow a null character are not compared) from the array pointed to by s1 to the array pointed to by s2. The strncasecmp function returns an integer greater than, equal to, or less than zero, accordingly as the possibly null-terminated array pointed to by s1 is greater than, equal to, or less than the possibly null-terminated array pointed to by s2.
Definition at line 425 of file string_test.c.
Referenced by test_strncasecmp().
char * manoj_strncat (char * dest_p, const char * src_p, size_t n)
7.21.3.2 The strncat function
Parameters:
src_p The source string
dest_p The destination the source string is appended to
n The number of bytes appended
Returns:
The strncat function returns the value of dest_p.
The strncat function appends not more than n characters (a null character and characters that follow it are not appended) from the array pointed to by src_p to the end of the string pointed to by dest_p. The initial character of src_p overwrites the null character at the end of dest_p. If copying takes place between objects that overlap, the behavior is undefined.
Definition at line 299 of file string_test.c.
Referenced by test_strncat().
int manoj_strncmp (const char * s1, const char * s2, size_t n)
7.21.4.4 The strncmp function Synopsis
Parameters:
s1 The first of two strings to be compared
s2 The second of two strings to be compared
n The number of bytes compared
Returns:
The strncmp function returns an integer
The strncmp function compares not more than n characters (characters that follow a null character are not compared) from the array pointed to by s1 to the array pointed to by s2. The strncmp function returns an integer greater than, equal to, or less than zero, accordingly as the possibly null-terminated array pointed to by s1 is greater than, equal to, or less than the possibly null-terminated array pointed to by s2.
Definition at line 355 of file string_test.c.
Referenced by test_strncmp().
char * manoj_strncpy (char * dest_p, const char * src_p, size_t n)
7.21.2.4 The strncpy function
Parameters:
src_p The source string
dest_p The destination the source string is copied to
n The number of bytes copied
Returns:
The strncpy function returns the value of dest_p.
The strncpy function copies not more than n characters (characters that follow a null character are not copied) from the array pointed to by src_p to the array pointed to by dest_p. if there is no null byte among the first n bytes of src_p, the result will not be null-terminated.
In the case where the length of src_p is less than that of n, the remainder of dest_p will be padded with nulls.
Definition at line 234 of file string_test.c.
Referenced by test_strncpy().
char * manoj_strrchr (const char * str_p, int c)
7.21.5.5 The strrchr function
Parameters:
str_p The string to search in
c The character being searched for.
Returns:
A pointer to the located charcter, or NULL
The strrchr function locates the last occurrence of c (converted to a char) in the string pointed to by str_p. The terminating null character is considered to be part of the string. The strchr function returns a pointer to the located character, or a null pointer if the character does not occur in the string.
Definition at line 481 of file string_test.c.
Referenced by test_strrchr().
char * manoj_strstr (const char * haystack, const char * needle)
7.21.5.7 The strstr function
Parameters:
haystack The string space to search in
needle The string to search for
Returns:
The strstr function returns a pointer to the located string, or NULL
The strstr function locates the first occurrence in the string pointed to by haystack of the sequence of characters (excluding the terminating null character) in the string pointed to by needle.
The strstr function returns a pointer to the located string, or a null pointer if the string is not found. If needle points to a string with zero length, the function returns haystack.
This implementation uses the Boyer-Moore algorithm. This algorithm searches for the pattern in a window that slides along the string to be searched. It is as if we have opened a window on the text to allow us to see only pat_lenght characters. Later, the window is slid to the right, allowing us to view other positions. The text of the pattern is ompared to the text exposed in the window, in a right to left order. In case of a mimatch, the window is slid over and the match restarted. The value of Boyer-Moore is that the window is slid over by more than one character (which is what the brute force method does), and this improes the efficiency of the algorithm, since we do not look at unfeasible positions to start matching. The amount by which we slide the window over is the maximum safe value (we do not want to slide the window too far, in case we miss a match.
How much we can skip is determined by thte following hueristics:
1.
The bad character rule: looking just at the character that didn't match
2.
The Good suffix rule: Looking at the suffix matched so far
The bad character rule.
Look at the character in the window that is being compared at the moment. In case of a mismatch, if the character does not occur in the search pattern at all, then there is no possibility that that character can be part of a match, and any instance of the pattern in the text must start to the right of the mismatched character, so the whole window can be slid over just beyond the character. (In other words, any orientation of the window that spans the mismatched charactercan't result in a match). So, if we had already matched m charactrers from the right hand side of the window, the window slides patlenght - m steps in this case.
Observation 1: If char in the window is known not to occur in the pattern, then there is no need to consider the possibility of the pattern occuring anywhere bedore the current char. If we had already matched d chars, the window shifts by patlen -d characters.
If the mismatched character does occur in the pattern, we need to slide the window over until the character in the pattern matches the character in the string. If the character occuers multiple times in the pattern, we need to slide the rightmost occurance of the character over the text in the string; however, sometimes that means sliding the window backwards, which we know can't be right. So at the very least, the minimum skip is at least one charactrer.
Observation 2: If the rightmost occurrence of the character being tested is d characters from the rightmost character in the pattern, then we can slide down d characters without looking for matches, to align the character in the text and in the pattern. If we slide any less than d, the characters won't match.(We need to allow for any characters already matched when we slide the window, since what we really are doing is to align the characters).
Uses knowledge of one character in the text, the character that is current;ly being examined.
The Good Suffix Hueristic
This hueristic applies for patterns with repeating strings. The bad charcter hueristic shall also work for patterns with repeating subpatterns, but the search will not be as eficient as possible. By examining partial matches and repeats in the search pattern, it is possible to make more drastic shifts in the window and match more rapidly. This hueristic represents the largest skip which can be made until the characters that have been matched coincide with another sequence in the pattern. Thus, we use our knowledge of a substring that exists in the text to help determine the safe shift. Any new position of the pattern that overlaps the current postion in the text _must_ match the characters we already know exist at this location (since we have matched them), since otherwise a mismatch is inevitable. In addition, the character that caused a mismatch right now must match its counterpart in the pattern in the new shift, or else the same mimatch would occur again.
The amount we shift is the lenght of the longest suffix of the matched pattern that matches a prefix of the pattern.
Definition at line 683 of file string_test.c.
References errno.
Referenced by test_strstr().
char * manoj_strtok (char * str_p, const char * delim)
7.21.5.8 The strtok function
Parameters:
str_p The string to be tokenized
delim The string conmtaining the list of token separators
Returns:
The strtok function returns a pointer to the first token, or NULL
A sequence of calls to the strtok function breaks the string pointed to by str_p into a sequence of tokens, each of which is delimited by a character from the string pointed to by delim. The first call in the sequence has a non-null first argument; subsequent calls in the sequence have a null first argument. The separator string pointed to by delim may be different from call to call.
The first call in the sequence searches the string pointed to by str_p for the first character that is not contained in the current separator string pointed to by delim. If no such character is found, then there are no tokens in the string pointed to by s1 and the strtok function returns a null pointer. If such a character is found, it is the start of the first token.
The strtok function then searches from there for a character that is contained in the current separator string. If no such character is found, the current token extends to the end of the string pointed to by s1, and subsequent searches for a token will return a null pointer. If such a character is found, it is overwritten by a null character, which terminates the current token. The strtok function saves a pointer to the following character, from which the next search for a token will start.
Each subsequent call, with a null pointer as the value of the first argument, starts searching from the saved pointer and behaves as described above.
The implementation shall behave as if no library function calls the strtok function.
The strtok function returns a pointer to the first character of a token, or a null pointer if there is no token.
This function modifies its first argument. The strtok() function uses a static buffer while parsing, so it's not thread safe. The strtok() function cannot be used on constant strings.
Definition at line 548 of file string_test.c.
Referenced by test_strtok().
char * manoj_strtok_r (char * str_p, const char * delim, char ** ptrptr)
The strtok_r function.
Parameters:
str_p The string to be tokenized
delim The string conmtaining the list of token separators
ptrptr Pointer to a user allocated buffer
Returns:
The strtok function returns a pointer to the first token, or NULL
This is a POSIX extention, and is not a ANSI C function. The strtok_r() function is a reentrant version of the strtok() function, which instead of using its own static buffer, requires a pointer to a user allocated char*. This pointer, the ptrptr parameter, must be the same while parsing the same string.
This function modifies its first argument, and cannot be used on constant strings.
Definition at line 604 of file string_test.c.
Referenced by test_strtok_r().
int strcasecmp (const char * s1, const char * s2)
Referenced by test_strcasecmp().
int strncasecmp (const char * s1, const char * s2, size_t n)
Referenced by test_strncasecmp().
char* strtok_r (char * s, const char * delim, char ** ptrptr)
Referenced by test_strtok_r().
int test_strcasecmp (void)
Test the manoj_strcasecmp function.
Returns:
0 on success, a negative integer on failure
Definition at line 1316 of file string_test.c.
References manoj_strcasecmp(), sign, strcasecmp(), and strings_to_test.
Referenced by main().
int test_strcat (void)
Test the manoj_strcat function.
Returns:
0 on success, a negative integer on failure
Definition at line 1128 of file string_test.c.
References manoj_strcat(), and strings_to_test.
Referenced by main().
int test_strchr (void)
Test the manoj_strnchr function.
Returns:
0 on success, a negative integer on failure
Definition at line 1392 of file string_test.c.
References manoj_strchr(), and strings_to_test.
Referenced by main().
int test_strcmp (void)
Test the manoj_strcmp function.
Returns:
0 on success, a negative integer on failure
Definition at line 1233 of file string_test.c.
References manoj_strcmp(), sign, and strings_to_test.
Referenced by main().
int test_strcpy (void)
Test the manoj_strcpy function.
Returns:
0 on success, a negative integer on failure
Definition at line 1000 of file string_test.c.
References manoj_strcpy(), and strings_to_test.
Referenced by main().
int test_strdup (void)
Test the manoj_strdup function.
Returns:
0 on success, a negative integer on failure
Definition at line 1082 of file string_test.c.
References manoj_strdup(), and strings_to_test.
Referenced by main().
int test_strlen (void)
Test the manoj_strlen function.
Returns:
0 on success, a negative integer on failure
Definition at line 964 of file string_test.c.
References manoj_strlen(), and strings_to_test.
Referenced by main().
int test_strncasecmp (void)
Test the manoj_strncat function.
Returns:
0 on success, a negative integer on failure
Definition at line 1354 of file string_test.c.
References manoj_strncasecmp(), sign, strings_to_test, and strncasecmp().
Referenced by main().
int test_strncat (void)
Test the manoj_strncat function.
Returns:
0 on success, a negative integer on failure
Definition at line 1176 of file string_test.c.
References manoj_strncat(), and strings_to_test.
Referenced by main().
int test_strncmp (void)
Test the manoj_strncat function.
Returns:
0 on success, a negative integer on failure
Definition at line 1274 of file string_test.c.
References manoj_strncmp(), sign, and strings_to_test.
Referenced by main().
int test_strncpy (void)
Test the manoj_strncpy function.
Returns:
0 on success, a negative integer on failure
Definition at line 1039 of file string_test.c.
References manoj_strncpy(), and strings_to_test.
Referenced by main().
int test_strrchr (void)
Test the manoj_strnchr function.
Returns:
0 on success, a negative integer on failure
Definition at line 1428 of file string_test.c.
References manoj_strrchr(), and strings_to_test.
Referenced by main().
int test_strstr (void)
Test the manoj_strtsr function.
Returns:
0 on success, a negative integer on failure
Definition at line 1604 of file string_test.c.
References manoj_strstr(), and strings_to_test.
Referenced by main().
int test_strtok (void)
Test the manoj_strtok function.
Returns:
0 on success, a negative integer on failure
Definition at line 1464 of file string_test.c.
References manoj_strtok().
Referenced by main().
int test_strtok_r (void)
Test the manoj_strtok_r function.
Returns:
0 on success, a negative integer on failure
Definition at line 1533 of file string_test.c.
References manoj_strtok_r(), and strtok_r().
Referenced by main().
Variable Documentation
int errno
Referenced by manoj_strstr().
const char* strings_to_test[]
Initial value:
 
  {
   'This ia a longish text string, but not that long, at that',
   'The long jump \0 and some trailing text at-that',
   '',
   'Some more test strings',
   'Yet another one',
   'what-finally-stops--at-at-that point',
   'aksdy923492p4 p39475 q0349750[q3hf30q79340 320496t034 03q495609324uy509y',
   'character is considered to be part of the string. The chr at-that point',
   0
  }
A set of test strings used for regression testing.
Definition at line 946 of file string_test.c.
Referenced by test_strcasecmp(), test_strcat(), test_strchr(), test_strcmp(), test_strcpy(), test_strdup(), test_strlen(), test_strncasecmp(), test_strncat(), test_strncmp(), test_strncpy(), test_strrchr(), and test_strstr().
const char* version [static]
Initial value:
 
  '$Id: string_test.c,v 1.6 2003/03/03 01:36:47 srivasta Exp $'
Definition at line 16 of file string_test.c.
Referenced by main().
Author
Generated automatically by Doxygen for TEST_STRINGS from the source code.